name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action@v2
        with:
          install-lib: false

      - name: Run tests
        uses: tree-sitter/parser-test-action@v2

  query:
    name: Validate queries
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action@v2
        with:
          install-lib: false

      - name: Build parser
        run: tree-sitter build

      - name: Set up ts_query_ls
        run: curl -fL https://github.com/ribru17/ts_query_ls/releases/latest/download/ts_query_ls-x86_64-unknown-linux-gnu.tar.gz | tar -xz

      - name: Check queries
        run: ./ts_query_ls check -f queries/
